language: php

matrix:
    include:
        - php: 7.2
        - php: 7.1
          env: deps='dev'
        - php: 7.1
          env: lint=1
          sudo: required
          services:
              - docker
          addons:
              apt:
                  packages:
                      - docker-ce

    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - if [[ ! $deps ]]; then composer update --prefer-dist --no-progress --no-suggest --ansi; fi
    - if [[ $deps = 'dev' ]]; then composer config minimum-stability dev && composer config prefer-stable false && composer update --prefer-dist --no-progress --no-suggest --ansi ; fi
    - if [[ $deps = 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
    - |
        if [[ $deps = 'dev' ]]; then
            export SYMFONY_DEPRECATIONS_HELPER=weak
        else
            export SYMFONY_DEPRECATIONS_HELPER=strict
        fi
    - if [[ ! $lint ]]; then vendor/bin/phpunit --verbose; fi
    - if [[ $lint = 1 ]]; then make ci; fi
